### ISSUE TITLE
Minor: upgrading stanford dependency would break anything? 

### ISSUE THREAD

**Issue by danyaljj** [microth/PathLSTM#12]
Would anything break if I use version 3.7.0 for Stanford dependency?

**Comment by microth** [comment]
What dependencies does the CogComp depparse model use? That's the one I'll use to retrain the SRL model. Everything else will lakely make things break (at least a little bit). //cc @christos-c

**Comment by danyaljj** [comment]
My question was with regards to your current "pre-illinois-built" branch, which uses corenlp parsing (3.6.0). Have you tried using 3.7.0? (the latest version). (Based on your previous response, I guess the answer is no)

**Comment by microth** [comment]
The "pre-illinois-built" branch uses the mate preprocessing pipeline (anna-3.x dependency), which is trained on CoNLL-2009 dependencies. The CoreNLP component is only used for tokenization.

**Comment by microth** [comment]
(As far as I remember, @christos-c  added CoreNLP 3.6.0 to the pom file. Not sure whether this would have been necessary. Only Stanford's WSJTokenizer is needed--but maybe it was not available as a separate dependency?)

**Comment by danyaljj** [comment]
I see. Looks like nothing breaks. Cool.

**Comment by christos-c** [comment]
Sorry for not responding to this sooner, but yes, the main reason I added the dependency was the tokenizer. The new dep parser doesn't need anything from Stanford.
