### ISSUE TITLE
Compilation error: "package se.lth.cs.srl.features does not exist"

### ISSUE THREAD

**Issue by beneyal** [microth/PathLSTM#15]
Hello,

I downloaded all dependencies and tried to `mvn compile`, but getting the above error.

A simple grep showed that 45 source files are importing this non-existing package. I tried switching to master branch, just to be sure, but no luck.

Thank you for your time :)

**Comment by microth** [comment]
Oh, I see what's going wrong there. I fixed the name of the package but did not update the imports. This should be fixed now. Please pull the latest revision from the repository (pre-illinois-built / default branch) and try again.

**Comment by beneyal** [comment]
Works like a charm, thanks!
