### ISSUE TITLE
Where do i download the models from?

### ISSUE THREAD

**Issue by nandinicbit1981** [microth/PathLSTM#6]
Where can i download the models from as stated below?

LEMMA_MODEL=models/lemma-eng.model
POS_MODEL=models/tagger-eng.model
PARSER_MODEL=models/parse-eng.model
SRL_MODEL=models/srl-ACL2016-eng.model

**Comment by microth** [comment]
> LEMMA_MODEL=models/lemma-eng.model
> POS_MODEL=models/tagger-eng.model
> PARSER_MODEL=models/parse-eng.model
>

See line 2 under "Dependencies" in the README file.

> SRL_MODEL=models/srl-ACL2016-eng.model
>

See line 4 under "Dependencies" in the README file.
