### ISSUE TITLE
How can we get the end sign of the argument consisting of multiple words?

### ISSUE THREAD

**Issue by yuchenlin** [microth/PathLSTM#7]
Hi, Michael. 

We are wondering if you can tell us how to know where the last term of a argument is. 
For example, "My room contains a book, a dog and a cat."  
In the demo web site, we can see that "a book, a dog and a cat" is the A1 of contain.01. 
But in the table below (and out.txt) we cannot know that the cat is the last word of A1. 
Should I change the code or something? 

Thank you very much.

**Comment by microth** [comment]
Hi Bill,

you can reconstruct the full argument span, and find out what the first/last word of an argument is, by recursively adding all syntactic dependants of an argument head word to that span. You'll find the head of each word in column 10 in the CoNLL output format (cf. http://ufal.mff.cuni.cz/conll2009-st/task-description.html). Alternatively, you can also use the getSpan() method in the Word class:

  https://github.com/microth/PathLSTM/blob/pre-illinois-built/src/main/java/se/lth/cs/srl/corpus/Word.java#L579

Cheers,
Michael

**Comment by yuchenlin** [comment]
Thank you very much. We are trying it.
