### ISSUE TITLE
Some nouns are considered as predicates incorrectly.

### ISSUE THREAD

**Issue by yuchenlin** [microth/PathLSTM#8]
Hi, Micheal 

For example, the result of sentence "My cat is sitting on my book." label "cat" and "book" to be cat.01 and book.01. But cat and book are nouns in this sentence (which is correctly identified in the POS column). 

Shouldn't each predicate be a VB*?   I am quite confused.

Bill

**Comment by microth** [comment]
Hi Bill,

Semantic roles are not restricted to verbs. The model is trained on a corpus that contains annotations derived from PropBank and NomBank. More info on the latter can be found here: http://nlp.cs.nyu.edu/meyers/NomBank.html

If you are only interested in the roles of arguments of verbs, then yes, you can ignore every predicate that does not have a POS of VB*.

Cheers,
Michael
